vfio/migration: Free resources when vfio_migration_realize fails
RH-Author: Cédric Le Goater <clg@redhat.com>
RH-MergeRequest: 179: vfio: live migration support
RH-Bugzilla: 2192818
RH-Acked-by: Eric Auger <eric.auger@redhat.com>
RH-Acked-by: Miroslav Rezanina <mrezanin@redhat.com>
RH-Commit: [25/28] b3ab8d3443d4bc12a689dc7d88a94da315814bb7 (clegoate/qemu-kvm-c9s)

Bugzilla: https://bugzilla.redhat.com/2192818

commit 2b43b2995b02
Author: Zhenzhong Duan <zhenzhong.duan@intel.com>
Date:   Mon Jul 3 15:15:08 2023 +0800

    vfio/migration: Free resources when vfio_migration_realize fails

    When vfio_realize() succeeds, hot unplug will call vfio_exitfn()
    to free resources allocated in vfio_realize(); when vfio_realize()
    fails, vfio_exitfn() is never called and we need to free resources
    in vfio_realize().

    In the case that vfio_migration_realize() fails,
    e.g: with -only-migratable & enable-migration=off, we see below:

    (qemu) device_add vfio-pci,host=81:11.1,id=vfio1,bus=root1,enable-migration=off
    0000:81:11.1: Migration disabled
    Error: disallowing migration blocker (--only-migratable) for: 0000:81:11.1: Migration is disabled for VFIO device

    If we hotplug again we should see same log as above, but we see:
    (qemu) device_add vfio-pci,host=81:11.1,id=vfio1,bus=root1,enable-migration=off
    Error: vfio 0000:81:11.1: device is already attached

    That's because some references to VFIO device isn't released.
    For resources allocated in vfio_migration_realize(), free them by
    jumping to out_deinit path with calling a new function
    vfio_migration_deinit(). For resources allocated in vfio_realize(),
    free them by jumping to de-register path in vfio_realize().

    Signed-off-by: Zhenzhong Duan <zhenzhong.duan@intel.com>
    Fixes: a22651053b59 ("vfio: Make vfio-pci device migration capable")
    Reviewed-by: Cédric Le Goater <clg@redhat.com>
    Reviewed-by: Joao Martins <joao.m.martins@oracle.com>
    Signed-off-by: Cédric Le Goater <clg@redhat.com>

Signed-off-by: Cédric Le Goater <clg@redhat.com>

Patch-name: kvm-vfio-migration-Free-resources-when-vfio_migration_re.patch
Patch-id: 137
Patch-present-in-specfile: True