target/ppc/cpu-models: Fix ppc_cpu_aliases list for RHEL
RH-Author: Murilo Opsfelder Araújo <muriloo@linux.ibm.com>
RH-MergeRequest: 81: target/ppc/cpu-models: remove extraneous "#endif"
RH-Commit: [1/1] 5fff003ad3deb84c6a8e69ab90552a31edb3b058 (mopsfelder/centos-stream-src-qemu-kvm)
RH-Bugzilla: 2081022
RH-Acked-by: Miroslav Rezanina <mrezanin@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>

The commit b9d28ecdedaf ("Enable/disable devices for RHEL") removed the
"#if 0" from the beginning of the ppc_cpu_aliases list, which broke the
build on ppc64le:

    ../target/ppc/cpu-models.c:904:2: error: #endif without #if
    #endif
     ^
    1 error generated.

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2081022

Fixes: b9d28ecdedaf (Enable/disable devices for RHEL)
Signed-off-by: Murilo Opsfelder Araujo <muriloo@linux.ibm.com>

Patch-name: kvm-target-ppc-cpu-models-Fix-ppc_cpu_aliases-list-for-R.patch
Patch-id: 23
Patch-present-in-specfile: True